-- Premium Staycations — Phase 1
-- 10. Supplier-side booking records and vouchers

-- Retry classification. The distinction matters more than the retry itself:
-- a deterministic failure cannot succeed on retry, and an indeterminate one
-- may already have created a booking at the supplier.
create type supplier_failure_class as enum ('deterministic', 'indeterminate');

create table external_bookings (
  id                uuid primary key default gen_random_uuid(),
  booking_id        uuid not null references bookings(id) on delete cascade,

  -- Which component this record satisfies. Without it the confirmation guard
  -- can only count rows, and a booking with two API components and two
  -- confirmations for the same component would pass.
  quote_item_id     uuid references quote_items(id),

  adapter           text not null,                    -- 'webbeds' | 'mock'
  supplier_ref      text not null,
  status            external_booking_status not null,

  -- Sent on every book() call and searchable via findByReference(). This is
  -- what makes a retry after a timeout safe: before retrying we ask the
  -- supplier whether the previous attempt landed.
  idempotency_key   text not null,
  attempt           int not null default 1,
  failure_class     supplier_failure_class,
  failure_detail    text,

  free_cancel_until timestamptz,
  net_cost          numeric not null,
  currency          text not null default 'AED',

  -- Tax treatment is per-contract and is read from the API response, never
  -- assumed. Null means unknown, and unknown must surface as a task rather
  -- than being priced as either inclusive or exclusive.
  net_rate_tax_inclusive boolean,
  taxes_included    jsonb,

  raw_response      jsonb,
  created_at        timestamptz not null default now(),

  constraint external_bookings_net_cost_positive check (net_cost >= 0),
  constraint external_bookings_failure_has_class
    check (status <> 'failed' or failure_class is not null)
);

-- One live supplier booking per attempt key. A replayed book() that reaches
-- the supplier twice cannot produce two confirmed rows here.
create unique index external_bookings_idempotency_idx
  on external_bookings (adapter, idempotency_key);

create index external_bookings_booking_idx on external_bookings (booking_id);
create index external_bookings_supplier_ref_idx on external_bookings (adapter, supplier_ref);

-- Components whose tax treatment we could not determine. The Bookings screen
-- and the task queue both read this.
create index external_bookings_tax_unknown_idx on external_bookings (booking_id)
  where net_rate_tax_inclusive is null;

comment on column external_bookings.idempotency_key is
  'Generated by us before the first book() attempt and reused across retries. '
  'findByReference(idempotencyKey) reconciles before any retry.';

comment on column external_bookings.net_rate_tax_inclusive is
  'Null = unknown. Never price an unknown component; raise a task.';

comment on column external_bookings.failure_class is
  'deterministic (sold out, price moved, invalid guest) goes straight to '
  'failed_rollback with no backoff. indeterminate (timeout, 5xx, reset) is '
  'reconciled via findByReference before a retry.';

-- ---------------------------------------------------------------------------
-- free_cancel_until is copied onto the booking so the finance agent can flag
-- approaching deadlines without joining out. The earliest component deadline
-- wins — that is the moment the booking as a whole stops being free to cancel.

create or replace function sync_booking_free_cancel_until()
returns trigger
language plpgsql
as $$
declare
  v_booking_id uuid := coalesce(new.booking_id, old.booking_id);
begin
  update bookings b
  set free_cancel_until = (
    select min(eb.free_cancel_until)
    from external_bookings eb
    where eb.booking_id = v_booking_id
      and eb.status = 'confirmed'
      and eb.free_cancel_until is not null
  )
  where b.id = v_booking_id;

  return null;
end;
$$;

create trigger external_bookings_sync_free_cancel
  after insert or update or delete on external_bookings
  for each row execute function sync_booking_free_cancel_until();

-- ---------------------------------------------------------------------------
-- Vouchers
--
-- Issued for contracted extras at confirmation. No voucher, no confirmation —
-- enforced in migration 13.

create sequence voucher_code_seq start 1;

create or replace function generate_voucher_code()
returns text
language sql
volatile
as $$
  select 'PSV-'
      || to_char(now() at time zone 'Asia/Dubai', 'YYMM')
      || '-'
      || lpad(nextval('voucher_code_seq')::text, 5, '0');
$$;

create table vouchers (
  id                uuid primary key default gen_random_uuid(),
  booking_id        uuid not null references bookings(id) on delete cascade,
  product_id        uuid references products(id),
  quote_item_id     uuid references quote_items(id),

  code              text unique not null default generate_voucher_code(),
  redemption_method redemption_method not null,

  valid_from        date,
  valid_to          date,
  redeemed_at       timestamptz,
  pdf_url           text,

  -- Operators may reissue, which supersedes rather than mutates. The original
  -- row is retained so a disputed redemption can be traced.
  reissued_from     uuid references vouchers(id),
  superseded_at     timestamptz,
  created_at        timestamptz not null default now(),

  constraint vouchers_dates_ordered
    check (valid_to is null or valid_from is null or valid_to >= valid_from)
);

create index vouchers_booking_idx on vouchers (booking_id);
create index vouchers_active_idx on vouchers (booking_id) where superseded_at is null;

comment on table vouchers is
  'One voucher per contracted quote item. Reissue supersedes via '
  'reissued_from; rows are never deleted.';
