/**
 * Premium Staycations — Phase 1
 * The supplier interface.
 *
 * Everything above this line — package assembly, the admin UI, the Phase 2
 * agents — talks to this and never to WebBeds directly. The interface is
 * deliberately small: Phase 1 needs to find rooms, price them, book them, and
 * find out what happened when a book() call did not come back cleanly.
 *
 * The property the whole design rests on is that every component confirms
 * instantly. There is no on-request path here, and adding one is a Phase 2
 * conversation, not a quiet extension of this interface.
 */

import type {
  ExternalBooking,
  Guest,
  PropertyContent,
  StayQuote,
  StaySearch,
} from './types';

export interface SupplierAdapter {
  /**
   * Written verbatim to properties.adapter and external_bookings.adapter, and
   * half of the unique key that makes idempotency keys safe across suppliers.
   */
  readonly name: string;

  /** Full content pull, for refreshing the properties cache. */
  listProperties(): Promise<PropertyContent[]>;

  getProperty(externalPropertyId: string): Promise<PropertyContent | null>;

  /** Availability and net rates. Returns an empty array when nothing is bookable. */
  search(criteria: StaySearch): Promise<StayQuote[]>;

  /**
   * Take the offer.
   *
   * The idempotency key is generated by us before the first attempt and reused
   * across every retry of the same component, which is what makes recovery
   * possible: the supplier can recognise a replay, and findByReference can ask
   * after the fact whether an attempt landed.
   *
   * Throws a SupplierError. Read its failureClass before deciding what to do —
   * see errors.ts, and never retry an indeterminate failure without calling
   * findByReference first.
   */
  book(
    quote: StayQuote,
    guests: Guest[],
    idempotencyKey: string,
  ): Promise<ExternalBooking>;

  /**
   * "Did my attempt land?"
   *
   * Null means the supplier has no record of that key, which is the only
   * evidence that justifies a retry after an indeterminate failure. A
   * non-null answer means a booking exists and must be adopted, not repeated.
   */
  findByReference(idempotencyKey: string): Promise<ExternalBooking | null>;

  /**
   * Release a booking we are rolling back.
   *
   * Present because failed_rollback is reachable with a confirmed component
   * already at the supplier: the payment succeeded, one of two rooms then
   * failed, and the room that did confirm has to be given back. Returns the
   * record in its cancelled state.
   */
  cancel(supplierRef: string, reason: string): Promise<ExternalBooking>;
}
